<?php
\SYSTEM\autoload::registerFolder(dirname(__FILE__),'');
require_once dirname(__FILE__).'/default_page/autoload.inc';
require_once dirname(__FILE__).'/default_list/autoload.inc';
require_once dirname(__FILE__).'/default_article/autoload.inc';
require_once dirname(__FILE__).'/default_impressum/autoload.inc';
require_once dirname(__FILE__).'/default_search/autoload.inc';
require_once dirname(__FILE__).'/article/autoload.inc';